/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EzFacMan;


import databaseTables.RoomsManager;
import databaseTables.campusManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali
 */
public class CommentSearch extends javax.swing.JFrame {

    ResultSet rs;
    EZFacUI ezFac;
    MapPanel mapdisplay;

    public CommentSearch() {
        initComponents();
        previous.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomPopUp = new javax.swing.JFrame();
        roomInfoPopup = new javax.swing.JPanel();
        roomAreaLabel = new javax.swing.JLabel();
        roomTypedes = new javax.swing.JLabel();
        roomFOAPALName = new javax.swing.JLabel();
        roomFOAPAL = new javax.swing.JLabel();
        roomNumber = new javax.swing.JLabel();
        roomFloor = new javax.swing.JLabel();
        roomBuildingName = new javax.swing.JLabel();
        roomCampus = new javax.swing.JLabel();
        campusCode = new javax.swing.JTextField();
        buildingName = new javax.swing.JTextField();
        floorName = new javax.swing.JTextField();
        roomNum = new javax.swing.JTextField();
        departmentCode = new javax.swing.JTextField();
        departmentName = new javax.swing.JTextField();
        roomType = new javax.swing.JTextField();
        roomArea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentBox = new javax.swing.JTextArea();
        next = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        commentField = new javax.swing.JTextField();
        SeatchBtn = new javax.swing.JButton();

        roomPopUp.setMinimumSize(new java.awt.Dimension(450, 425));

        roomInfoPopup.setMinimumSize(new java.awt.Dimension(275, 225));

        javax.swing.GroupLayout roomInfoPopupLayout = new javax.swing.GroupLayout(roomInfoPopup);
        roomInfoPopup.setLayout(roomInfoPopupLayout);
        roomInfoPopupLayout.setHorizontalGroup(
            roomInfoPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roomInfoPopupLayout.setVerticalGroup(
            roomInfoPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        roomAreaLabel.setText("Room Area: ");

        roomTypedes.setText("Room Type: ");

        roomFOAPALName.setText("FOAPAL Name: ");

        roomFOAPAL.setText("FOAPAL: ");

        roomNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roomNumber.setText("Room Number: ");

        roomFloor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roomFloor.setText("Floor: ");

        roomBuildingName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roomBuildingName.setText("Building Name: ");

        roomCampus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roomCampus.setText("Campus: ");

        campusCode.setEditable(false);
        campusCode.setMinimumSize(new java.awt.Dimension(300, 25));
        campusCode.setPreferredSize(new java.awt.Dimension(180, 28));

        buildingName.setEditable(false);
        buildingName.setMinimumSize(new java.awt.Dimension(300, 25));

        floorName.setEditable(false);
        floorName.setMinimumSize(new java.awt.Dimension(300, 25));

        roomNum.setEditable(false);
        roomNum.setMinimumSize(new java.awt.Dimension(300, 25));
        roomNum.setPreferredSize(new java.awt.Dimension(180, 28));

        departmentCode.setMinimumSize(new java.awt.Dimension(300, 25));

        departmentName.setMinimumSize(new java.awt.Dimension(300, 25));

        roomType.setMinimumSize(new java.awt.Dimension(300, 25));

        roomArea.setMinimumSize(new java.awt.Dimension(300, 25));

        jLabel1.setText("Comments:");

        commentBox.setColumns(20);
        commentBox.setRows(5);
        commentBox.setMinimumSize(new java.awt.Dimension(300, 25));
        jScrollPane1.setViewportView(commentBox);

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        previous.setText("previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomPopUpLayout = new javax.swing.GroupLayout(roomPopUp.getContentPane());
        roomPopUp.getContentPane().setLayout(roomPopUpLayout);
        roomPopUpLayout.setHorizontalGroup(
            roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPopUpLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(roomInfoPopup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(roomPopUpLayout.createSequentialGroup()
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomPopUpLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roomPopUpLayout.createSequentialGroup()
                                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roomAreaLabel)
                                    .addComponent(roomTypedes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(roomType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roomArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(roomPopUpLayout.createSequentialGroup()
                                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(roomPopUpLayout.createSequentialGroup()
                                        .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(roomPopUpLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(roomCampus))
                                            .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(roomFOAPALName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(roomNumber, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(roomFOAPAL)
                                            .addComponent(roomFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(5, 5, 5))
                                    .addGroup(roomPopUpLayout.createSequentialGroup()
                                        .addComponent(roomBuildingName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(departmentCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(roomNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(floorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(departmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(buildingName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(campusCode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(roomPopUpLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        roomPopUpLayout.setVerticalGroup(
            roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPopUpLayout.createSequentialGroup()
                .addComponent(roomInfoPopup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campusCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildingName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomBuildingName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomFloor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNumber))
                .addGap(4, 4, 4)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomFOAPAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomFOAPALName)
                    .addComponent(departmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypedes)
                    .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomAreaLabel)
                    .addComponent(roomArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next)
                    .addComponent(previous))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        commentField.setText("Enter a Comment .. ");

        SeatchBtn.setText("Search");
        SeatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(SeatchBtn)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SeatchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
       try {
            if(rs.previous()){
                showRoomInfo();
            }else
                
               previous.setEnabled(false);
             } catch (SQLException ex) {
            Logger.getLogger(CommentSearch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
         try {
            if(rs.next()){
                showRoomInfo();
                 previous.setEnabled(true);
            }else{
                
            
                rs.previous();
            JOptionPane.showMessageDialog(null, "No More results");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CommentSearch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_nextActionPerformed

    private void SeatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatchBtnActionPerformed

        try {
            rs = RoomsManager.getByComment(commentField.getText());

            if (rs != null) {

                if (rs.next()) {
                    showRoomInfo();

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CommentSearch.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CommentSearch.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_SeatchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommentSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SeatchBtn;
    public javax.swing.JTextField buildingName;
    public javax.swing.JTextField campusCode;
    public javax.swing.JTextArea commentBox;
    private javax.swing.JTextField commentField;
    public javax.swing.JTextField departmentCode;
    public javax.swing.JTextField departmentName;
    public javax.swing.JTextField floorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next;
    private javax.swing.JButton previous;
    public javax.swing.JTextField roomArea;
    private javax.swing.JLabel roomAreaLabel;
    private javax.swing.JLabel roomBuildingName;
    private javax.swing.JLabel roomCampus;
    private javax.swing.JLabel roomFOAPAL;
    private javax.swing.JLabel roomFOAPALName;
    private javax.swing.JLabel roomFloor;
    public javax.swing.JPanel roomInfoPopup;
    public javax.swing.JTextField roomNum;
    private javax.swing.JLabel roomNumber;
    public javax.swing.JFrame roomPopUp;
    public javax.swing.JTextField roomType;
    private javax.swing.JLabel roomTypedes;
    // End of variables declaration//GEN-END:variables
private void showRoomInfo() throws SQLException {

    
        departmentName.setText(rs.getString("FOAPAL_name"));
        departmentCode.setText(rs.getString("FOAPAL_code"));
        floorName.setText(rs.getString("floor_name"));
        commentBox.setText(rs.getString("comments"));
        roomNum.setText(rs.getString("room_num"));
        buildingName.setText(rs.getString("building_name"));
        roomType.setText(rs.getString("room_type_des"));
        roomArea.setText(rs.getString("room_area_sqft"));
        campusCode.setText(rs.getString("campus_name"));
        roomPopUp.setVisible(true);

    }

}
