package EzFacMan;

import ParseSVGData.SVGParser;
import databaseTables.*;

import java.awt.Color;
import static java.awt.Color.blue;
import static java.awt.Color.white;
import java.awt.event.WindowEvent;
import javax.swing.JFileChooser;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * User Interface class for EZ-Fac program.
 *
 * @author Mike Manalo
 * @author Nathan Jack
 * @author Nick Killion
 * @author Ali
 */
public class EZFacUI extends javax.swing.JFrame {

    File selectedFile = null;
    public ArrayList<String> allcampuses = new ArrayList<String>();
    private ArrayList<String> allbuildings = new ArrayList<String>();
    private ArrayList<String> allfloors = new ArrayList<String>();
    public String dBuilding;
    public static String dCampus;
    public String dFloor;
    floors f = floorsManager.displayAllfloors();
    campus c = campusManager.displayAllCampuses();
    building b = buildingManager.displayAllBuildings();

    /**
     * Creates new form NewJFrame
     *
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public EZFacUI() throws SQLException, ClassNotFoundException {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass()
                .getResource("/Images/CornerIcon.png")));
        allfloors.addAll(f.getAllFloors());
        allcampuses.addAll(c.getAllcampuses());
        allbuildings.addAll(b.getAllbuildings());
        allfloors.stream().forEach((s) -> {
            floorDropdown.addItem(s);
        });
        allcampuses.stream().forEach((s) -> {
            campusDropdown.addItem(s);
        });
        allbuildings.stream().forEach((s) -> {
            buildingDropdown.addItem(s);
        });
        buildingDropdown.setEnabled(false);
        floorDropdown.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomPopUp = new javax.swing.JFrame();
        roomInfoPopup = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        roomTypedes = new javax.swing.JLabel();
        roomFOAPALName = new javax.swing.JLabel();
        roomFOAPAL = new javax.swing.JLabel();
        roomNumber = new javax.swing.JLabel();
        roomFloor = new javax.swing.JLabel();
        roomBuildingName = new javax.swing.JLabel();
        roomCampus = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        campusCode = new javax.swing.JTextField();
        buildingName = new javax.swing.JTextField();
        floorName = new javax.swing.JTextField();
        roomNum = new javax.swing.JTextField();
        departmentCode = new javax.swing.JTextField();
        departmentName = new javax.swing.JTextField();
        roomType = new javax.swing.JTextField();
        roomArea = new javax.swing.JTextField();
        updateChange = new javax.swing.JButton();
        deptColorChooser = new javax.swing.JColorChooser();
        pdfMapChooser = new javax.swing.JFileChooser();
        quitConfirmation = new javax.swing.JDialog();
        quitConfirmYes = new javax.swing.JButton();
        quitConfirmCancel = new javax.swing.JButton();
        quitConfirmQuestion = new javax.swing.JLabel();
        addNewMapFrame = new javax.swing.JFrame();
        addMapPDF = new javax.swing.JButton();
        addMapCSV = new javax.swing.JButton();
        cautionLabel = new javax.swing.JLabel();
        importButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        pdfName = new javax.swing.JLabel();
        csvName = new javax.swing.JLabel();
        csvMapChooser = new javax.swing.JFileChooser();
        mainPanel = new javax.swing.JPanel();
        mapDisplay = new EzFacMan.MapPanel();
        campusDropdown = new javax.swing.JComboBox();
        campusLabel = new javax.swing.JLabel();
        buildingLabel = new javax.swing.JLabel();
        buildingDropdown = new javax.swing.JComboBox();
        floorLabel = new javax.swing.JLabel();
        floorDropdown = new javax.swing.JComboBox();
        menuBar = new javax.swing.JMenuBar();
        fileButton = new javax.swing.JMenu();
        addNewMap = new javax.swing.JMenuItem();
        quitButton = new javax.swing.JMenuItem();
        settingsButton = new javax.swing.JMenu();
        modDeptColor = new javax.swing.JMenuItem();
        resetDeptColors = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpButton = new javax.swing.JMenu();
        userManualButton = new javax.swing.JMenuItem();
        aboutButton = new javax.swing.JMenuItem();

        roomPopUp.setResizable(false);
        roomPopUp.setSize(new java.awt.Dimension(400, 350));

        roomInfoPopup.setMinimumSize(new java.awt.Dimension(275, 225));

        javax.swing.GroupLayout roomInfoPopupLayout = new javax.swing.GroupLayout(roomInfoPopup);
        roomInfoPopup.setLayout(roomInfoPopupLayout);
        roomInfoPopupLayout.setHorizontalGroup(
            roomInfoPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roomInfoPopupLayout.setVerticalGroup(
            roomInfoPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setText("Room Area: ");

        roomTypedes.setText("Room Type: ");

        roomFOAPALName.setText("FOAPAL Name: ");

        roomFOAPAL.setText("FOAPAL: ");

        roomNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roomNumber.setText("Room Number: ");

        roomFloor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roomFloor.setText("Floor: ");

        roomBuildingName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roomBuildingName.setText("Building Name: ");

        roomCampus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roomCampus.setText("Campus: ");

        jButton2.setText("Select Color");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        campusCode.setText("Main Campus");

        buildingName.setText("jTextField1");

        floorName.setText("jTextField2");

        roomNum.setText("jTextField3");

        departmentCode.setText("jTextField4");

        departmentName.setText("jTextField5");

        roomType.setText("jTextField6");

        roomArea.setText("jTextField7");

        updateChange.setText("Update");
        updateChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomPopUpLayout = new javax.swing.GroupLayout(roomPopUp.getContentPane());
        roomPopUp.getContentPane().setLayout(roomPopUpLayout);
        roomPopUpLayout.setHorizontalGroup(
            roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPopUpLayout.createSequentialGroup()
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomPopUpLayout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(roomInfoPopup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomPopUpLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomNumber)
                            .addComponent(roomFOAPAL)
                            .addComponent(roomFOAPALName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomTypedes)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roomPopUpLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buildingName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roomPopUpLayout.createSequentialGroup()
                                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roomBuildingName)
                                    .addComponent(roomCampus)
                                    .addComponent(roomFloor))
                                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roomPopUpLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(floorName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPopUpLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campusCode, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(roomPopUpLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateChange)))
                .addContainerGap())
        );
        roomPopUpLayout.setVerticalGroup(
            roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPopUpLayout.createSequentialGroup()
                .addComponent(roomInfoPopup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campusCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomBuildingName)
                    .addComponent(buildingName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomFloor)
                    .addComponent(floorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNumber)
                    .addComponent(roomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomFOAPAL)
                    .addComponent(departmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomFOAPALName)
                    .addComponent(departmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypedes)
                    .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(roomArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(roomPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(updateChange))
                .addContainerGap())
        );

        deptColorChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AbstractColorChooserPanel[] panels=deptColorChooser.getChooserPanels();
        for(AbstractColorChooserPanel p:panels){
            String displayName=p.getDisplayName();
            switch (displayName) {
                case "HSV":
                deptColorChooser.removeChooserPanel(p);
                break;
                case "HSL":
                deptColorChooser.removeChooserPanel(p);
                break;
                case "CMYK":
                deptColorChooser.removeChooserPanel(p);
                break;
            }
        }

        pdfMapChooser.removeChoosableFileFilter(pdfMapChooser.getAcceptAllFileFilter());
        FileNameExtensionFilter pdfFilter = new FileNameExtensionFilter("PDF", "pdf");
        pdfMapChooser.addChoosableFileFilter(pdfFilter);
        pdfMapChooser.setAccessory(addNewMap);
        pdfMapChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pdfMapChooserPropertyChange(evt);
            }
        });

        quitConfirmation.setTitle("Quit Confirmation");
        quitConfirmation.setAlwaysOnTop(true);
        quitConfirmation.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        quitConfirmation.setMinimumSize(new java.awt.Dimension(500, 300));
        quitConfirmation.setResizable(false);
        quitConfirmation.setType(java.awt.Window.Type.POPUP);
        quitConfirmation.setLocationRelativeTo(null);

        quitConfirmYes.setText("Yes");
        quitConfirmYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitConfirmYesActionPerformed(evt);
            }
        });

        quitConfirmCancel.setText("Cancel");
        quitConfirmCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitConfirmCancelActionPerformed(evt);
            }
        });

        quitConfirmQuestion.setText("Are you sure you want to quit?");

        javax.swing.GroupLayout quitConfirmationLayout = new javax.swing.GroupLayout(quitConfirmation.getContentPane());
        quitConfirmation.getContentPane().setLayout(quitConfirmationLayout);
        quitConfirmationLayout.setHorizontalGroup(
            quitConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quitConfirmationLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(quitConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quitConfirmationLayout.createSequentialGroup()
                        .addComponent(quitConfirmYes)
                        .addGap(36, 36, 36)
                        .addComponent(quitConfirmCancel))
                    .addComponent(quitConfirmQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, Short.MAX_VALUE))
                .addGap(129, 129, 129))
        );
        quitConfirmationLayout.setVerticalGroup(
            quitConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quitConfirmationLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(quitConfirmQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addGroup(quitConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitConfirmYes)
                    .addComponent(quitConfirmCancel))
                .addGap(53, 53, 53))
        );

        addNewMapFrame.setMinimumSize(new java.awt.Dimension(500, 400));
        addNewMapFrame.setResizable(false);
        addNewMapFrame.setLocationRelativeTo(null);

        addMapPDF.setText("Choose a map (.pdf)");
        addMapPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMapPDFActionPerformed(evt);
            }
        });

        addMapCSV.setText("Choose a spreadsheet (.csv)");
        addMapCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMapCSVActionPerformed(evt);
            }
        });

        cautionLabel.setText("Note: Make sure the map and spreadsheet correspond to the same floor");

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        csvName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout addNewMapFrameLayout = new javax.swing.GroupLayout(addNewMapFrame.getContentPane());
        addNewMapFrame.getContentPane().setLayout(addNewMapFrameLayout);
        addNewMapFrameLayout.setHorizontalGroup(
            addNewMapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewMapFrameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cautionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(198, 198, 198))
            .addGroup(addNewMapFrameLayout.createSequentialGroup()
                .addGroup(addNewMapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewMapFrameLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(importButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(156, 156, 156)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addNewMapFrameLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(addMapCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))
                    .addGroup(addNewMapFrameLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(addMapPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(84, 84, 84))
                    .addGroup(addNewMapFrameLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(pdfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(126, 126, 126))
                    .addGroup(addNewMapFrameLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(csvName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(107, 107, 107)))
                .addGap(234, 234, 234))
        );
        addNewMapFrameLayout.setVerticalGroup(
            addNewMapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewMapFrameLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(addMapPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pdfName)
                .addGap(29, 29, 29)
                .addComponent(addMapCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(csvName)
                .addGap(36, 36, 36)
                .addComponent(cautionLabel)
                .addGap(18, 18, 18)
                .addGroup(addNewMapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importButton)
                    .addComponent(cancelButton))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        csvMapChooser.removeChoosableFileFilter(csvMapChooser.getAcceptAllFileFilter());
        FileNameExtensionFilter csvFilter = new FileNameExtensionFilter("CSV", "csv");
        csvMapChooser.addChoosableFileFilter(csvFilter);
        csvMapChooser.setAccessory(addNewMap);
        csvMapChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvMapChooserActionPerformed(evt);
            }
        });
        csvMapChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                csvMapChooserPropertyChange(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mapDisplayLayout = new javax.swing.GroupLayout(mapDisplay);
        mapDisplay.setLayout(mapDisplayLayout);
        mapDisplayLayout.setHorizontalGroup(
            mapDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        mapDisplayLayout.setVerticalGroup(
            mapDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        campusDropdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campusDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Main" }));
        campusDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campusDropdownActionPerformed(evt);
            }
        });

        campusLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campusLabel.setText("Campus");

        buildingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buildingLabel.setText("Building");

        buildingDropdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buildingDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ritter Hall (004)" }));
        buildingDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingDropdownActionPerformed(evt);
            }
        });

        floorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floorLabel.setText("Floor");

        floorDropdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floorDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2nd Floor" }));
        floorDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(campusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campusDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buildingLabel)
                        .addGap(18, 18, 18)
                        .addComponent(buildingDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(floorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(floorDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mapDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campusDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buildingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buildingDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floorDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mapDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileButton.setText("File");

        addNewMap.setText("Add New Map");
        addNewMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewMapActionPerformed(evt);
            }
        });
        fileButton.add(addNewMap);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        fileButton.add(quitButton);

        menuBar.add(fileButton);

        settingsButton.setText("Settings");

        modDeptColor.setText("Change Department Color");
        modDeptColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modDeptColorActionPerformed(evt);
            }
        });
        settingsButton.add(modDeptColor);

        resetDeptColors.setText("Revert to Default Colors");
        resetDeptColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDeptColorsActionPerformed(evt);
            }
        });
        settingsButton.add(resetDeptColors);

        menuBar.add(settingsButton);

        jMenu1.setText("Search");

        jMenuItem1.setText("by Room Number");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("by Comment");
        jMenu1.add(jMenuItem2);

        menuBar.add(jMenu1);

        helpButton.setText("Help");

        userManualButton.setText("User Manual");
        userManualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManualButtonActionPerformed(evt);
            }
        });
        helpButton.add(userManualButton);

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        helpButton.add(aboutButton);

        menuBar.add(helpButton);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campusDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campusDropdownActionPerformed
        dCampus = (String) campusDropdown.getSelectedItem();
        String sqlString = "'" + dCampus + "'";

        if (dCampus != null) {

            building bb = null;
            try {
                buildingDropdown.removeAllItems();

                bb = buildingManager.display(sqlString);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EZFacUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            allbuildings.removeAll(allbuildings);
            allbuildings.addAll(bb.getAllbuildings());

            allbuildings.stream().forEach((s) -> {
                buildingDropdown.addItem(s);

            });
            buildingDropdown.setEnabled(true);
            floorDropdown.setEnabled(false);

        }

    }//GEN-LAST:event_campusDropdownActionPerformed

    private void floorDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorDropdownActionPerformed

    private void mainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseClicked

        try {

            Rooms RoomsObject = RoomsManager.displayCertainRooms();

            roomNum.setText(RoomsObject.getRoom_num());
            departmentCode.setText(RoomsObject.getFOAPAL_code().toString());
            roomType.setText(RoomsObject.getRoom_type_des());
            floorName.setText(RoomsObject.getFloor_name());
            departmentName.setText(RoomsObject.getFOAPAL_name());

            //  dispose();
        } catch (SQLException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);

        }
        roomPopUp.setVisible(true);

    }//GEN-LAST:event_mainPanelMouseClicked

    private void buildingDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingDropdownActionPerformed
        dBuilding = (String) buildingDropdown.getSelectedItem();

        if (dBuilding != null) {
            floors ff = null;
            try {
                floorDropdown.removeAllItems();

                ff = floorsManager.display(dBuilding);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EZFacUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            allfloors.removeAll(allfloors);
            allfloors.addAll(ff.getAllFloors());

            allfloors.stream().forEach((s) -> {
                floorDropdown.addItem(s);

            });

        }
        System.out.println(allfloors.toString());
        floorDropdown.setEnabled(true);
    }//GEN-LAST:event_buildingDropdownActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void resetDeptColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDeptColorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetDeptColorsActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        int q = JOptionPane.showConfirmDialog(null, "Are you sure?", "You are quiting the program!", JOptionPane.YES_NO_OPTION);

        if (q == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_quitButtonActionPerformed

    private void addNewMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewMapActionPerformed
        addNewMapFrame.setVisible(true);
    }//GEN-LAST:event_addNewMapActionPerformed
    /**
     * Creates and opens new color chooser after user clicks on Modify
     * Department Color button.
     * <p>
     * Code adapted from:
     * http://www.java2s.com/Tutorial/Java/0240__Swing/RemovingaColorChooserPanelfromaJColorChooserDialog.htm.
     *
     * @param evt an event listener that listens for user to click on Modify
     * Department Color button
     */
    private void modDeptColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modDeptColorActionPerformed
        deptColorChooser = new javax.swing.JColorChooser();
        AbstractColorChooserPanel[] oldPanels = deptColorChooser.getChooserPanels();
        for (int i = 0; i < oldPanels.length; i++) {
            String clsName = oldPanels[i].getClass().getName();
            if (clsName.equals("javax.swing.colorchooser.DefaultRGBChooserPanel")) {
                deptColorChooser.removeChooserPanel(oldPanels[i]);
            } else if (clsName.equals("javax.swing.colorchooser.DefaultHSBChooserPanel")) {
                deptColorChooser.removeChooserPanel(oldPanels[i]);
            } else if (clsName.equals("javax.swing.colorchooser.DefaultHSYKChooserPanel")) {
                deptColorChooser.removeChooserPanel(oldPanels[i]);
            }
        }
        Color newColor = deptColorChooser.showDialog(this, "Choose a Department Color", white);

    }//GEN-LAST:event_modDeptColorActionPerformed
    /**
     * Opens the About .pdf using the desktop's default program.
     * <p>
     * Code adapted from: http://www.javabeat.net/java-open-word-document/
     *
     * @param evt listens for the user to click the About menu option
     */
    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed

        File aboutFile = null;
        String os = System.getProperty("os.name").toLowerCase();
        if (os.contains("win")) {
            aboutFile = new File("C:\\Users\\" + System.getProperty("user.name") + "\\Documents\\NetBeansProjects\\EzFacMan\\AboutEZFac.pdf");
        } else if (os.contains("mac")) {
            aboutFile = new File("/Users/" + System.getProperty("user.name") + "/NetBeansProjects/EzFacMan/AboutEZFac.pdf");
        } else {
            JOptionPane.showMessageDialog(null, "Your Operating System is not supported!", "Error!", JOptionPane.OK_OPTION);
        }
        aboutFile.setReadOnly();
        try {
            //Open the file using Desktop class
            Desktop.getDesktop().open(aboutFile);
        } catch (IOException exception) {
            exception.printStackTrace();
        }
    }//GEN-LAST:event_aboutButtonActionPerformed

    /**
     * Exits the program.
     *
     * @param evt an event that is triggered when user clicks yes in quit
     * confirmation dialog
     */
    private void quitConfirmYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitConfirmYesActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_quitConfirmYesActionPerformed
    /**
     * Closes the quit confirmation dialog box.
     *
     * @param evt an event listener that is triggered when user clicks cancel on
     * quit confirmation dialog
     */
    private void quitConfirmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitConfirmCancelActionPerformed
        quitConfirmation.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_quitConfirmCancelActionPerformed
    /**
     * Opens the .pdf file chooser to select a new map.
     *
     * @param evt an event listener that is triggered when user clicks on button
     * to select .pdf.
     */
    private void addMapPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMapPDFActionPerformed
        // TODO add your handling code here:
        int returnVal1 = pdfMapChooser.showOpenDialog(EZFacUI.this);
    }//GEN-LAST:event_addMapPDFActionPerformed
    /**
     * Opens the .csv file chooser to select a new spreadsheet.
     *
     * @param evt an event listener that is triggered when user clicks on button
     * to select .csv.
     */
    private void addMapCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMapCSVActionPerformed
        int returnVal2 = csvMapChooser.showOpenDialog(EZFacUI.this);
    }//GEN-LAST:event_addMapCSVActionPerformed

    private void csvMapChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvMapChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csvMapChooserActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        SVGParser parser = new SVGParser(selectedFile.getPath());
        mapDisplay.setRoomList(parser.parse());
        mapDisplay.setVisible(true);

        Graphics g = mapDisplay.getGraphics();
        g.setColor(Color.blue);
        mapDisplay.repaint();

    }//GEN-LAST:event_importButtonActionPerformed
    /**
     * Closes the addNewMapFrame dialog box.
     *
     * @param evt an event listener that is triggered when user clicks cancel on
     * addNewMapFrame dialog
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        addNewMapFrame.dispatchEvent(new WindowEvent(addNewMapFrame, WindowEvent.WINDOW_CLOSING));
        // pdfName.setText(null);
        //   csvName.setText(null);
    }//GEN-LAST:event_cancelButtonActionPerformed
    /**
     * Changes pdfName label to correspond with the name of the .pdf that user
     * previously selected.
     * <p>
     * Code adapted from:
     * http://stackoverflow.com/questions/8428548/java-jfilechooser-how-to-show-selected-file-in-a-textfield.
     *
     * @param evt an event listener that listens for a property change in the
     * pdfMapChooser
     */
    private void pdfMapChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pdfMapChooserPropertyChange

        if (JFileChooser.SELECTED_FILE_CHANGED_PROPERTY.equals(evt.getPropertyName())) {
            JFileChooser pdfMapChooser = (JFileChooser) evt.getSource();
            File oldFile = (File) evt.getOldValue();
            File newFile = (File) evt.getNewValue();

            // The selected file should always be the same as newFile
            File curFile = pdfMapChooser.getSelectedFile();
            selectedFile = curFile;
            PDFCustomFilter pdfFilter = new PDFCustomFilter();
            if (pdfFilter.accept(selectedFile)) {
                pdfName.setText(curFile.getName());
                pdfName.setForeground(blue);
            } else {
                System.err.println("File is not a valid PDF");
            }
        } else if (JFileChooser.SELECTED_FILES_CHANGED_PROPERTY.equals(
                evt.getPropertyName())) {
            JFileChooser pdfMapChooser = (JFileChooser) evt.getSource();
            File[] oldFiles = (File[]) evt.getOldValue();
            File[] newFiles = (File[]) evt.getNewValue();

            // Get list of selected files
            // The selected files should always be the same as newFiles
            File[] files = pdfMapChooser.getSelectedFiles();
        }
    }//GEN-LAST:event_pdfMapChooserPropertyChange
    /**
     * Changes csvName label to correspond with the name of the .csv that user
     * previously selected.
     * <p>
     * Code adapted from:
     * http://stackoverflow.com/questions/8428548/java-jfilechooser-how-to-show-selected-file-in-a-textfield.
     *
     * @param evt an event listener that listens for a property change in the
     * csvMapChooser
     */
    private void csvMapChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_csvMapChooserPropertyChange
        if (JFileChooser.SELECTED_FILE_CHANGED_PROPERTY.equals(evt.getPropertyName())) {
            JFileChooser csvMapChooser = (JFileChooser) evt.getSource();
            File csvOldFile = (File) evt.getOldValue();
            File csvNewFile = (File) evt.getNewValue();

            // The selected file should always be the same as newFile
            File csvCurFile = csvMapChooser.getSelectedFile();

            CSVCustomFilter csvFilter = new CSVCustomFilter();
            if (csvFilter.accept(csvCurFile)) {
                csvName.setText(csvCurFile.getName());
                csvName.setForeground(blue);
            } else {
                System.err.println("File is not a valid CSV");
            }

        } else if (JFileChooser.SELECTED_FILES_CHANGED_PROPERTY.equals(
                evt.getPropertyName())) {
            JFileChooser csvMapChooser = (JFileChooser) evt.getSource();
            File[] csvOldFiles = (File[]) evt.getOldValue();
            File[] csvNewFiles = (File[]) evt.getNewValue();

            // Get list of selected files
            // The selected files should always be the same as newFiles
            File[] csvFiles = csvMapChooser.getSelectedFiles();
        }
    }//GEN-LAST:event_csvMapChooserPropertyChange
    /**
     * Opens the User Manual using the desktop's default program.
     * <p>
     * Code adapted from: http://www.javabeat.net/java-open-word-document/
     *
     * @param evt listens for the user to click the User Manual menu option
     */
    private void userManualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManualButtonActionPerformed

        File file = null;
        String os = System.getProperty("os.name").toLowerCase();
        if (os.contains("win")) {
            file = new File("C:\\Users\\" + System.getProperty("user.name") + "\\Documents\\NetBeansProjects\\EzFacMan\\UserManualV1.doc");

        } else if (os.contains("mac")) {
            file = new File("/Users/" + System.getProperty("user.name") + "/NetBeansProjects/EzFacMan/UserManualV1.doc");
        } else {
            JOptionPane.showMessageDialog(null, "Your Operating System is not supported!", "Error!", JOptionPane.OK_OPTION);
        }
        file.setReadOnly();
        try {
            //Open the file using Desktop class
            Desktop.getDesktop().open(file);
        } catch (IOException exception) {
            exception.printStackTrace();
        }
    }//GEN-LAST:event_userManualButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SearchPanel S = null;
        try {
            S = new SearchPanel();
        } catch (SQLException ex) {
            Logger.getLogger(EZFacUI.class.getName()).log(Level.SEVERE, null, ex);
            S.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EZFacUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        S.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void updateChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateChangeActionPerformed

    }//GEN-LAST:event_updateChangeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
    * The button to open the about page.
    */
    private javax.swing.JMenuItem aboutButton;
    /**
    * The button to launch the .csv file chooser.
    */
    private javax.swing.JButton addMapCSV;
    /**
    * The button to launch the .pdf file chooser.
    */
    private javax.swing.JButton addMapPDF;
    /**
    * The button to add a new map.
    */
    private javax.swing.JMenuItem addNewMap;
    /**
    * The frame to import a new map.
    */
    private javax.swing.JFrame addNewMapFrame;
    /**
    * This dropdown box selects a building to show on spreadsheet display.
    */
    private javax.swing.JComboBox buildingDropdown;
    /**
    * The label for the building selected from the dropdown box.
    */
    private javax.swing.JLabel buildingLabel;
    private javax.swing.JTextField buildingName;
    private javax.swing.JTextField campusCode;
    /**
    * This dropdown box selects a campus to show on spreadsheet display.
    */
    private javax.swing.JComboBox campusDropdown;
    /**
    * The label for the campus selected from the dropdown box.
    */
    private javax.swing.JLabel campusLabel;
    /**
    * The button to exit the import new map frame.
    */
    private javax.swing.JButton cancelButton;
    /**
    * The label that warns user to select files corresponding to same floor.
    */
    private javax.swing.JLabel cautionLabel;
    /**
    * The file chooser to choose a .csv file.
    */
    private javax.swing.JFileChooser csvMapChooser;
    /**
    * The label displays the name of the .csv file selected.
    */
    private javax.swing.JLabel csvName;
    private javax.swing.JTextField departmentCode;
    private javax.swing.JTextField departmentName;
    /**
    * The color chooser to select a new department color.
    */
    private javax.swing.JColorChooser deptColorChooser;
    /**
    * The button for the file menu.
    */
    private javax.swing.JMenu fileButton;
    /**
    * This dropdown box selects a floor to show on spreadsheet display.
    */
    private javax.swing.JComboBox floorDropdown;
    /**
    * The label for the floor selected from the dropdown box.
    */
    private javax.swing.JLabel floorLabel;
    private javax.swing.JTextField floorName;
    /**
    * The button for the help menu.
    */
    private javax.swing.JMenu helpButton;
    /**
    * The button to import the selected .pdf and .csv files.
    */
    private javax.swing.JButton importButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    /**
    * This is the panel for the main window.
    */
    private javax.swing.JPanel mainPanel;
    private EzFacMan.MapPanel mapDisplay;
    /**
    * The menu for the main window.
    */
    private javax.swing.JMenuBar menuBar;
    /**
    * The button to modify department colors.
    */
    private javax.swing.JMenuItem modDeptColor;
    /**
    * The file chooser that selects a .pdf.
    */
    private javax.swing.JFileChooser pdfMapChooser;
    /**
    * The label displays name of the .pdf file selected.
    */
    private javax.swing.JLabel pdfName;
    /**
    * The button to exit the program.
    */
    private javax.swing.JMenuItem quitButton;
    /**
    * The "cancel" button to exit the program.
    */
    private javax.swing.JButton quitConfirmCancel;
    /**
    * The label that displays the quit confirmation question.
    */
    private javax.swing.JLabel quitConfirmQuestion;
    /**
    * The "yes" button to quit the program.
    */
    private javax.swing.JButton quitConfirmYes;
    /**
    * The dialog confirms that the user wants to quit.
    */
    private javax.swing.JDialog quitConfirmation;
    /**
    * The button to reset department colors. =
    */
    private javax.swing.JMenuItem resetDeptColors;
    private javax.swing.JTextField roomArea;
    private javax.swing.JLabel roomBuildingName;
    private javax.swing.JLabel roomCampus;
    private javax.swing.JLabel roomFOAPAL;
    private javax.swing.JLabel roomFOAPALName;
    private javax.swing.JLabel roomFloor;
    private javax.swing.JPanel roomInfoPopup;
    private javax.swing.JTextField roomNum;
    private javax.swing.JLabel roomNumber;
    private javax.swing.JFrame roomPopUp;
    private javax.swing.JTextField roomType;
    private javax.swing.JLabel roomTypedes;
    /**
    * The button for the settings menu.
    */
    private javax.swing.JMenu settingsButton;
    private javax.swing.JButton updateChange;
    /**
    * The button to open the user manual.
    */
    private javax.swing.JMenuItem userManualButton;
    // End of variables declaration//GEN-END:variables
}
